---
title: "Team"
author: "John Banta"
date: "10/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
defense <- read_excel('cyclonesFootball2018.xlsx', sheet='Defensive')
str(defense)
```

```{r}
offense <- read_excel('cyclonesFootball2018.xlsx', sheet='Offensive')
bio <- read_excel('cyclonesFootball2018.xlsx', sheet='Biography')
```


Cleaning
```{r}
library(dplyr)
library(tidyr)
offense$Name<-as.factor(offense$Name)
offense$Opponent_Opponent<-as.factor(offense$Opponent_Opponent)
defense$Opponent_Opponent<-as.factor(defense$Opponent_Opponent)
defense$Name<-as.factor(defense$Name)
bio$Weight<-as.numeric(bio$Weight)
colo<-c("Receiving_REC","Receiving_YDS","Receiving_TD","Rushing_ATT","Rushing_YDS","Rushing_TD","Passing_CMP-ATT","Passing_YDS","Passing_TD","Passing_INT")
offense[colo]<-sapply(offense[colo], as.numeric)
cold<-c("Tackles_Solo","Tackles_ASST","Tackles_TFL","Tackles_Sack","Turnover_FF","Turnover_FR","Turnover_INT","Pass_QBH","Pass_PB")
defense[cold]<-sapply(defense[cold],as.numeric)
bio<-separate(data=bio,col=Height,into=c("Feet","inc"),sep="\\-")
bio$Feet<-as.numeric(bio$Feet)
bio$inc<-as.numeric(bio$inc)
bio$height_in_inches<-(bio$Feet*12+bio$inc)
head(bio)
colb<-c("Name","Position","Class","Hometown","Highschool")
bio[colb]<-lapply(bio[colb],factor)
bioClean<-select(bio,-c("Feet","inc"))
head(bioClean)
defClean<-defense
offClean<-offense
sapply(offClean,class)
sapply(defClean,class)
sapply(bioClean,class)
```

